name: React CI/CD

on:
  push:
    branches: [ main, master ]
  pull_requests:
    branches: [ main, master ]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Set up Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '18'
        cache: 'npm'

    - name: Install dependencies
      run: npm ci

    - name: Run linting
      run: npm run lint
      if: success()

    - name: Run tests
      run: npm run test
      if: success()

    - name: Build project
      run: npm run build
      if: success()

    - name: Deploy to VPS
      if: success() && github.event_name == 'push'
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.VPS_HOST }}
        username: ${{ secrets.VPS_USERNAME }}
        key: ${{ secrets.VPS_SSH_KEY }}
        script: |
          cd /var/www/html
          git pull
          npm ci
          npm run build
            systemctl restart nginx

