name: React CI/CD

on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    environment: production

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'
          cache: 'npm'

      - name: Install dependencies
        run: npm ci

      - name: Run linting
        run: npm run lint
        if: success()

      - name: Build project
        run: npm run build
        if: success()

      - name: Deploy to VPS
        if: success() && github.event_name == 'push'
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.VPS_HOST }}
          username: ${{ secrets.VPS_USERNAME }}
          key: ${{ secrets.VPS_SSH_KEY }}
          script: |
            mkdir -p /tmp/new-build
            cp -r /var/www/html/* /tmp/new-build/ 2>/dev/null || true
            rm -rf /var/www/html/*
            cp -r /tmp/new-build/* /var/www/html/
            rm -rf /tmp/new-build
            
      - name: Upload build artifacts
        if: success() && github.event_name == 'push'
        uses: actions/upload-artifact@v3
        with:
          name: build-files
          path: build/
          
      - name: Deploy to VPS
        if: success() && github.event_name == 'push'
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.VPS_HOST }}
          username: ${{ secrets.VPS_USERNAME }}
          key: ${{ secrets.VPS_SSH_KEY }}
          source: "build/"
          target: "/var/www/html"
          strip_components: 1


