- name: Build project
  run: npm run build
  if: success()

- name: Deploy Front to VPS
  if: success() && github.event_name == 'push'
  uses: appleboy/ssh-action@master
  with:
    host: ${{ secrets.VPS_HOST }}
    username: ${{ secrets.VPS_USERNAME }}
    key: ${{ secrets.VPS_SSH_KEY }}
    script: |
      cd /home/dede/PokemonCenter/front
      git pull origin main
      npm ci
      npm run build
      sudo systemctl reload nginx